name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Release Name
        id: set_release_name
        run: echo "::set-output name=release_name::${GITHUB_REF#refs/tags/release:}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_release_name.outputs.release_name }}
          release_name: ${{ steps.set_release_name.outputs.release_name }}
          body: |
            Release ${{ steps.set_release_name.outputs.release_name }}
          draft: false
          prerelease: false

      - name: Create Release Archive
        run: |
          zip -r "MikScrollingBattleText ${{ steps.set_release_name.outputs.release_name }}.zip" MikScrollingBattleText
        working-directory: ${{ github.workspace }}

      - name: Upload Release Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./MikScrollingBattleText ${{ steps.set_release_name.outputs.release_name }}.zip"
          asset_name: "MikScrollingBattleText ${{ steps.set_release_name.outputs.release_name }}.zip"
          asset_content_type: application/zip
